apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-mvn-local-repo
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
      volumeName: mvndevstoragevolume